import { TransformNode, SceneLoader } from '@babylonjs/core';
import { applyModelPaint } from '../../../utils/modelPaint.js';

// BATCH-0 CALIBRATION PART — not game art. Generated by scripts/modelgen/calib_hull_axes.py.
// Markers: RED cone = Blender -Y (front under test), BLUE cube = Blender +X (right),
// GOLD disc = standard ring seat. Delete this module + registry entry after Batch 0.

const PAINT = { paintColor: null }; // keep marker colors — do NOT paint over them

export default {
  id: 'hull-calib',
  name: 'CALIB HULL',
  category: 'hull',
  stats: {},
  mountEmpty: 'turret',
  nativeTurret: null,

  async build(scene) {
    const result = await SceneLoader.ImportMeshAsync('', '/assets/models/tanks/parts/', 'calib_hull_axes.glb', scene);
    const mountNode = result.transformNodes.find(n => n.name === this.mountEmpty);
    const mount = mountNode ? mountNode.getAbsolutePosition().clone() : null;

    const root = new TransformNode('hull_calib_root', scene);
    const meshes = result.meshes.filter(m => m.name !== '__root__');
    for (const m of meshes) m.setParent(root);

    applyModelPaint(meshes, PAINT, scene, null);
    return { root, meshes, mount, ringCenter: mount };
  },
};
